### ISSUE TITLE
👋 Introduction

### ISSUE THREAD

**Issue by okjake** [GSG-G9/house-hunting-app#122]
Hi all!

Firstly sorry for the delay - I was sent an invite to your project earlier this week but I'm just catching up now.

I'm Jake, a product engineer in Spain, and I'll be helping out with some code reviews and trying to make myself useful! 

Most recently I've worked for [Auth0](https://auth0.com/) on CS infrastructure and [Polarr](https://creators.polarr.com/) writing a photo editor in React, I'm now working on something new (in stealth mode)

Looks like you've made a great start, I'll get up to speed with your project this weekend and then I'll try to check in roughly once a day and have a look at any open PRs, but feel free to request a review too.

I'll try and get an invite to your discord (Jake~) if you have any questions or if there's anything I can help with. In the meantime you can get me at jakepyne@gmail.com 

Feel free to close this issue, I don't want to clutter your backlog - just wanted to say hi!

**Comment by mAbadsa** [comment]
Welcome to the team! Our team is very happy to have you with us. Your experience will be of great benefit to the team.

**Comment by AdhamHaisami** [comment]
Hello Jake. Glad to see you around, We will be waiting for your review and advice. And I personally will ask for a review for some issues. Thank you!!

**Comment by yasmeenattallah** [comment]
hi jack it is very blessed to see you in our project and give us your review  , we are very excited to learn new   things from you ,welcome

**Comment by okjake** [comment]
Thanks all! Hope I can be of help.
